name: Deploy

on:
  push:
    tags:
    - v*

jobs:

  deploy-build:
    name: Deploy (*)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
        ~/.local/bin/conan config install https://github.com/iceshard-engine/conan-config.git
    - name: Create package
      run: |
        ~/.local/bin/conan create . moonscript-installer/0.5.0@iceshard/stable --profile clang-9.0-linux-x86_64
    - name: Deploy
      run: |
        ~/.local/bin/conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        ~/.local/bin/conan upload -r conan-iceshard moonscript-installer/0.5.0@iceshard/stable --all
